version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - cruzrtwin_mongo_data:/data/db

  orion:
    image: fiware/orion:3.10.0
    container_name: orion
    restart: always
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel DEBUG

volumes:
  cruzrtwin_mongo_data:
